"""Export the Pydantic planning wire contract for the Roamie mobile app."""

import json
from pathlib import Path

from roamie_agents.planning import PlanSelection


def typescript(schema):
    if "$ref" in schema:
        return schema["$ref"].split("/")[-1]
    if "anyOf" in schema:
        return " | ".join(typescript(item) for item in schema["anyOf"])
    if "enum" in schema:
        return " | ".join(json.dumps(item) for item in schema["enum"])
    kind = schema.get("type")
    if kind == "object":
        required = schema.get("required", [])
        return (
            "{ "
            + "; ".join(
                f"{name}{'' if name in required else '?'}: {typescript(value)}"
                for name, value in schema["properties"].items()
            )
            + " }"
        )
    if kind == "array":
        return f"({typescript(schema['items'])})[]"
    return {
        "string": "string",
        "integer": "number",
        "number": "number",
        "boolean": "boolean",
        "null": "null",
    }[kind]


schema = PlanSelection.model_json_schema()
text = "// Generated by ai-agents/scripts/export_roamie_mobile_contract.py.\n"
for name, value in schema["$defs"].items():
    text += f"export type {name} = {typescript(value)};\n"
Path("contracts/roamie-planning.ts").write_text(text)
